feat: add type icons
DeveloperKhan/pogo-web pull request #89
Opened 2021-03-23 21:10 UTC by FlorianKutz

Fixes #63

2021-03-23 21:20 UTC, DeveloperKhan requested changes
Looks great, but we already have svgs for each type icon. Would you be able to delete these .pngs and use the Icon component in `/components/icon`? The colors we use for each type can be found in `/common/css/colors.scss`.

2021-03-23 21:22 UTC, theking465 commented
In `src/components/team_member_selector` the types also need to be changed to icons.

2021-03-24 13:56 UTC, FlorianKutz commented
![Screenshot (1178)](https://user-images.githubusercontent.com/18531173/112322323-14bd9180-8cb1-11eb-82cd-fcbbcfa294b2.png)
![Screenshot (1179)](https://user-images.githubusercontent.com/18531173/112322326-15562800-8cb1-11eb-9d56-d1ff62fc669d.png)
Fixed

2021-03-24 17:58 UTC, DeveloperKhan approved these changes

2021-03-24 17:58 UTC, merged